package ec.edu.espe.Tutorias.Vo;

import java.io.Serializable;

public class AsistentesVo implements Serializable {

	private static final long serialVersionUID = 1L;
	private String UZTASISTENTES_CEDULA;
	private String UZTASISTENTES_ID;
	private String UZTASISTENTES_ESTUDIANTE;
	private String UZTASISTENTES_EMAIL;
	private String UZTASISTENTES_ESTADO;
	
	public AsistentesVo() {
		
	}

    public AsistentesVo(String UZTASISTENTES_CEDULA, String UZTASISTENTES_ID, String UZTASISTENTES_ESTUDIANTE, String UZTASISTENTES_EMAIL, String UZTASISTENTES_ESTADO  ) {
    	this.UZTASISTENTES_CEDULA=UZTASISTENTES_CEDULA;
    	this.UZTASISTENTES_ID=UZTASISTENTES_ID;
    	this.UZTASISTENTES_ESTUDIANTE=UZTASISTENTES_ESTUDIANTE;
    	this.UZTASISTENTES_EMAIL=UZTASISTENTES_EMAIL;
		
	}

	public String getUZTASISTENTES_ID() {
		return UZTASISTENTES_ID;
	}

	public void setUZTASISTENTES_ID(String uZTASISTENTES_ID) {
		UZTASISTENTES_ID = uZTASISTENTES_ID;
	}

	public String getUZTASISTENTES_ESTADO() {
		return UZTASISTENTES_ESTADO;
	}

	public void setUZTASISTENTES_ESTADO(String uZTASISTENTES_ESTADO) {
		UZTASISTENTES_ESTADO = uZTASISTENTES_ESTADO;
	}

	public String getUZTASISTENTES_ESTUDIANTE() {
		return UZTASISTENTES_ESTUDIANTE;
	}

	public void setUZTASISTENTES_ESTUDIANTE(String uZTASISTENTES_ESTUDIANTE) {
		UZTASISTENTES_ESTUDIANTE = uZTASISTENTES_ESTUDIANTE;
	}

	public String getUZTASISTENTES_EMAIL() {
		return UZTASISTENTES_EMAIL;
	}

	public void setUZTASISTENTES_EMAIL(String uZTASISTENTES_EMAIL) {
		UZTASISTENTES_EMAIL = uZTASISTENTES_EMAIL;
	}

	public String getUZTASISTENTES_CEDULA() {
		return UZTASISTENTES_CEDULA;
	}

	public void setUZTASISTENTES_CEDULA(String uZTASISTENTES_CEDULA) {
		UZTASISTENTES_CEDULA = uZTASISTENTES_CEDULA;
	}

}
